/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddItemForm: typeof import('./components/Inventory/AddItemForm.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InventoryList: typeof import('./components/Inventory/InventoryList.vue')['default']
    ModifyItemForm: typeof import('./components/Inventory/ModifyItemForm.vue')['default']
    ProductForm: typeof import('./components/ProductForm.vue')['default']
    ProductItem: typeof import('./components/ProductItem.vue')['default']
    ProductList: typeof import('./components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
